openapi: 3.0.1
info:
  title: monster-gelatinous-cube
  x-cortex-tag: monster-gelatinous-cube
x-cortex-custom-data:
  alignment: neutral
  challenge_rating: 2
  legendary: false
  source: dnd-5e
  type: ooze
x-cortex-owners:
- email: bestiary@dnd.com
x-cortex-tag: monster-gelatinous-cube
x-cortex-type: monster
